# Generated by Django 2.0.2 on 2018-02-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_followed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
